image: rambabusaravanan/firebase


cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  environment: Production
  script:
  - cd Presentation/app
  - yarn
  - yarn run build
  - firebase use winged-code --token $FIREBASE_DEPLOY_KEY
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  artifacts:
    paths:
     - build
  only:
  - master
